/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/pages/About.vue')['default']
    Banner: typeof import('./src/components/Section/Banner.vue')['default']
    BuyPackage: typeof import('./src/components/pages/BuyPackage.vue')['default']
    Contact: typeof import('./src/components/pages/Contact.vue')['default']
    Counter: typeof import('./src/components/Section/Counter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/pages/Home.vue')['default']
    Members: typeof import('./src/components/pages/Members.vue')['default']
    Navbar: typeof import('./src/components/Header/Navbar.vue')['default']
    Packages: typeof import('./src/components/pages/Packages.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
